apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: argocd-test-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/farbodbj/argocd-test-repo.git
  ref:
    branch: main
  secretRef:
    name: flux-git-credentials